language: python
    python:
      - "2.6"
      - "2.7"
      - "3.6.3"
    services:
      - sqlite3
    env:
      -DJANGO=2.2.4 DB=sqlite3
    install:
      - pip install -r requirements.txt
    before_script:
      # 
    script:
      - python manage.py test