dist: xenial
language: python
python:
  - 3.6.3
  
branches:
  only:
    - master

env:
  - DJANGO_VERSION=2.2.4

before_install:
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -r requirements.txt
  - python scripts/install-frontend.py

before_script:
  - cp test.env.ini env.ini

script:
  - python scripts/build-frontend.py
  - python scripts/run-tests.py
