dist: xenial
language: python
python:
  - 3.6.3

branches:
  only:
    - master

env:
  - DJANGO_VERSION=2.2.4

before_install:
  - openssl aes-256-cbc -K $encrypted_b628dea4aac4_key -iv $encrypted_b628dea4aac4_iv
    -in deploy_key.enc -out ./deploy_key -d
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@167.71.118.223 pwd
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -r requirements.txt
  - yarn install

before_script:
  - cp test.env.ini env.ini

script:
  - yarn run build
  - python run-tests.py