language: python
    python:
      - "2.6"
      - "2.7"
      - "3.6.3"

      branches:
        only:
        - master

    env:
      - DJANGO_VERSION=2.2.4

    install:
      - pip install -r requirements.txt
      
    script:
      - python manage.py test