# Generated by Django 2.2.4 on 2019-11-30 03:50

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('episodes', '0001_initial'), ('episodes', '0002_auto_20191127_0419'), ('episodes', '0003_auto_20191127_0438'), ('episodes', '0004_episode_tags'), ('episodes', '0005_auto_20191127_0441'), ('episodes', '0006_auto_20191127_0442'), ('episodes', '0007_episode_active')]

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=3)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='episodes/images/')),
                ('audio', models.FileField(default='assets/not-found.mp3', max_length=500, upload_to='episodes/audio/')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
