# Generated by Django 2.2.4 on 2019-11-27 03:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=3)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='episodes/images/')),
                ('audio', models.FileField(default='assets/not-found.mp3', max_length=500, upload_to='episodes/audio/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
