# Generated by Django 2.2.4 on 2019-11-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_squashed_0007_episode_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='tags',
        ),
    ]
