# Generated by Django 3.0.1 on 2019-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
