# Generated by Django 2.2.4 on 2019-11-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='genres',
            field=models.ManyToManyField(blank=True, to='episodes.Genre'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=models.ManyToManyField(blank=True, to='episodes.Tag'),
        ),
    ]
