# Generated by Django 2.2.4 on 2019-11-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_auto_20191127_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='active',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
