# Generated by Django 2.2.4 on 2019-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_episode_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
