# Generated by Django 2.2.4 on 2020-01-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_auto_20200115_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeThumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.IntegerField()),
                ('image', models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='episodes/images/thumbnails/')),
            ],
        ),
    ]
