# Generated by Django 2.2.4 on 2019-11-27 04:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('episodes', '0004_episode_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='tags',
        ),
        migrations.AddField(
            model_name='episode',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
