# Generated by Django 2.2.4 on 2019-11-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_auto_20191127_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
