# Generated by Django 3.1.14 on 2022-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_delete_episodethumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
