# Generated by Django 3.1.14 on 2023-01-20 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0007_episode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 22, 8, 9, 517706), null=True),
        ),
    ]
