# Generated by Django 3.1.14 on 2023-01-20 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0009_auto_20230119_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(default=None, max_length=500, upload_to='episodes/audio/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 22, 13, 57, 916764), null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(default=None, max_length=500, upload_to='episodes/images/'),
        ),
    ]
