# Generated by Django 3.1.14 on 2023-01-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0010_auto_20230119_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
