# Generated by Django 3.1.14 on 2023-01-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0012_auto_20230120_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True, help_text='Determines whether or not an episode will be visible on the front-end of the website.'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='featured',
            field=models.BooleanField(default=False, help_text='If featured, an episode will persist indefinitely without expiration. Even when featured, the episode must be active to be viewed in the front-end.'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(default=None, help_text='Used as the background image for the episode.', max_length=500, upload_to='episodes/images/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma separated. ex: "funk, house, soca disco".', max_length=255, null=True),
        ),
    ]
