# Generated by Django 6.0.6 on 2026-08-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_url', models.CharField(blank=True, help_text='URL that the UI will connect to to play the stream.', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Connections',
            },
        ),
    ]
