# Generated by Django 6.0.6 on 2026-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='call_in_number',
            field=models.CharField(blank=True, help_text='Number for the call-in line. Enter number with no special characters. ex: 5036103801', max_length=10, null=True),
        ),
    ]
