# Generated by Django 6.0.6 on 2026-06-10 21:45

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_show_pre_recorded_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='pre_recorded_show',
            field=models.FileField(blank=True, help_text='Optional upload field for pre-recorded shows. Files MUST be in MP3 format.', max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/seanpierce/www/introtorhythm.com/introtorhythm_backend')), upload_to='uploads/scheduler/'),
        ),
    ]
