# Generated by Django 2.2.4 on 2020-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.IntegerField(choices=[(0, '12 am'), (1, '1 am'), (2, '2 am'), (3, '3 am'), (4, '4 am'), (5, '5 am'), (6, '6 am'), (7, '7 am'), (8, '8 am'), (9, '9 am'), (10, '10 am'), (11, '11am'), (12, '12 pm'), (13, '1 pm'), (14, '2 pm'), (15, '3 pm'), (16, '4 pm'), (17, '5 pm'), (18, '6 pm'), (19, '7 pm'), (20, '8 pm'), (21, '9 pm'), (22, '10 pm'), (23, '11 pm')])),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('active', models.BooleanField(default=True)),
                ('pre_record', models.BooleanField(default=True)),
                ('audio', models.FileField(blank=True, max_length=500, upload_to='uploads/')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
