# Generated by Django 3.1.13 on 2022-02-16 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200115_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='show',
            old_name='audio',
            new_name='pre_record_audio',
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='show',
            name='day',
        ),
        migrations.RemoveField(
            model_name='show',
            name='pre_record',
        ),
    ]
