# Generated by Django 3.1.13 on 2022-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20220216_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
