# Generated by Django 3.1.14 on 2022-11-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20221027_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
