# Generated by Django 3.1.14 on 2022-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_show_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='end_time',
            new_name='end_date_time',
        ),
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=1),
        ),
    ]
