# Generated by Django 3.1.14 on 2022-11-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20221116_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='pre_record_audio',
        ),
        migrations.AddField(
            model_name='show',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
