# Generated by Django 3.1.14 on 2022-11-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_liverecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverecording',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
