# Generated by Django 3.1.14 on 2023-03-21 02:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_show_pre_recorded_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='pre_recorded_show',
            field=models.FileField(blank=True, help_text='Optional upload field for pre-recorded shows. Files MUST be in MP3 format.', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/Users/seanpierce/Code/Sites/introtorhythm.com'), upload_to='uploads/scheduler/'),
        ),
    ]
