# Generated by Django 2.2.4 on 2019-08-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
                ('image', models.CharField(max_length=250)),
                ('audio', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
