# Generated by Django 2.1.4 on 2019-08-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(default='Warm Up', max_length=250),
            preserve_default=False,
        ),
    ]
