# Generated by Django 2.2.4 on 2019-08-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_episode_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(default='assets/not-found.mp3', max_length=500, upload_to='episodes/audio/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='episodes/images/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
