# Generated by Django 2.2.4 on 2019-08-09 05:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_auto_20190806_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
