# Generated by Django 3.0.1 on 2019-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191214_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='img-12202019-09:11:46', max_length=50),
        ),
    ]
