# Generated by Django 2.2.4 on 2020-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191220_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='img-01152020-19:52:44', max_length=50),
        ),
    ]
