# Generated by Django 2.2.4 on 2020-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200115_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='img-01152020-19:55:03', max_length=50),
        ),
    ]
