# Generated by Django 2.2.4 on 2020-01-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200115_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='img-01152020-20:46:20', max_length=50),
        ),
    ]
