# Generated by Django 2.2.4 on 2020-01-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200115_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='img-01242020-13:27:32', max_length=50),
        ),
    ]
