# Generated by Django 2.2.10 on 2020-04-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200426_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'verbose_name_plural': 'Background Image'},
        ),
    ]
