# Generated by Django 3.1 on 2020-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200426_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
