# Generated by Django 3.1.14 on 2022-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_backgroundimage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='plain_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
