# Generated by Django 3.1.14 on 2022-10-28 23:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_content_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='info',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
