# Generated by Django 3.1.14 on 2022-10-28 23:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20221028_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
