# Generated by Django 3.1.14 on 2022-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20221028_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='plain_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
