# Generated by Django 3.1.14 on 2022-11-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_livecallout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livecallout',
            options={'verbose_name_plural': 'Live Callout'},
        ),
    ]
