# Generated by Django 3.1.14 on 2022-11-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20221114_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
