# Generated by Django 3.1.14 on 2022-11-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='active',
            field=models.BooleanField(default=False, help_text='Toggle used to show or not show the associated image on the "Live" page'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Image that will show as the background of the "Live" page', upload_to='content/images'),
        ),
    ]
