# Generated by Django 3.1.14 on 2023-01-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20221115_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, help_text='10-digit phone number used for call-in shows. No parentesis, or hyphens - just numbers.', max_length=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether or not the call-in number is active')),
            ],
            options={
                'verbose_name_plural': 'Call In Number',
            },
        ),
    ]
