name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via git pull
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ 22 }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            cd /home/seanpierce/www/introtorhythm.com
            git pull origin main

            cd introtorhythm_backend
            source ./venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 manage.py migrate
            deactivate

            export PATH="/home/seanpierce/.nvm/versions/node/v25.8.1/bin:$PATH"

            cd ../introtorhythm_frontend
            npm ci
            npm run build

            cd ./src/chat
            npx tsc --project tsconfig.server.json
            pm2 restart chat-server-prod

          EOF