name: remote ssh command

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: introtorhythm.com
          username: ${{ secrets.SSH_SERVER_AGENT_USER }}
          password: ${{ secrets.SSH_SERVER_AGENT_PASSWORD }}
          port: 22
          script: |
            cd /home/seanpierce/www/introtorhythm.com
            echo "========== Pulling Source ============"
            git pull origin master
            echo "========== Setting Up Environment ============"
            pip install --upgrade pip
            source venv/bin/activate
            echo "VIRTUAL ENV:" $VIRTUAL_ENV
            echo "========== Setting Up Environment ============"
            pip install -r ./requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            echo "========== Building Vue App =============="
            cd app
            yarn build
            echo "========== Restarting Environment =============="
            echo ${{ secrets.SSH_SERVER_AGENT_PASSWORD }} | sudo -S systemctl restart gunicorn
            echo ${{ secrets.SSH_SERVER_AGENT_PASSWORD }} | sudo -S systemctl restart nginx
            echo "=========== SUCCESS ============="
